spring.application.name=cabeleleila-leila

spring.datasource.url=jdbc:mysql://localhost:3306/salao_db
spring.datasource.username=root
spring.datasource.password=root123@

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true